-- =========================================================
-- Gravity Desk Buddy (GDB)
-- PostgreSQL Database Blueprint
-- Version: 2.0
--
-- Purpose:
-- Support the MVP focus loop while preserving the foundations
-- for developmental profiles, domains, and earned Orbits.
-- =========================================================

BEGIN;

-- =========================================================
-- 1. ORBITS
-- Permanent reference stock containing the six official Orbits.
-- Progression rules deliberately remain outside this table.
-- =========================================================

CREATE TABLE IF NOT EXISTS orbits (
    orbit_id SMALLINT PRIMARY KEY,
    orbit_name VARCHAR(100) NOT NULL UNIQUE,
    orbit_rank SMALLINT NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_orbit_rank_positive
        CHECK (orbit_rank > 0)
);

INSERT INTO orbits (
    orbit_id,
    orbit_name,
    orbit_rank,
    description
)
VALUES
    (1, 'Parallax Orbit', 1, 'Beginning the developmental journey.'),
    (2, 'Standard Candle Orbit', 2, 'Building greater consistency and clarity.'),
    (3, 'Spectroscopy Orbit', 3, 'Demonstrating deeper examination and applied reflection.'),
    (4, 'Event Horizon Orbit', 4, 'Engaging complex problems with stronger judgment.'),
    (5, 'Relativity Orbit', 5, 'Integrating multiple perspectives and systems.'),
    (6, 'Singularity Orbit', 6, 'Invitation-only recognition for exceptional development and contribution.')
ON CONFLICT (orbit_id) DO UPDATE
SET
    orbit_name = EXCLUDED.orbit_name,
    orbit_rank = EXCLUDED.orbit_rank,
    description = EXCLUDED.description;


-- =========================================================
-- 2. USERS
-- Base identity and account-level profile settings.
-- Authentication passwords will be handled outside this schema.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    display_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,

    profile_image_url TEXT,

    current_orbit_id SMALLINT NOT NULL DEFAULT 1,

    profile_visibility VARCHAR(20) NOT NULL DEFAULT 'private',
    show_buddy_publicly BOOLEAN NOT NULL DEFAULT TRUE,
    show_orbit_publicly BOOLEAN NOT NULL DEFAULT TRUE,
    show_domain_publicly BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_users_current_orbit
        FOREIGN KEY (current_orbit_id)
        REFERENCES orbits (orbit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_profile_visibility
        CHECK (
            profile_visibility IN (
                'private',
                'connections',
                'public'
            )
        )
);


-- =========================================================
-- 3. DOMAINS
-- Reusable list of fields in which users pursue development.
-- =========================================================

CREATE TABLE IF NOT EXISTS domains (
    domain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 4. USER DOMAIN JOURNEYS
-- Preserves how a user's developmental direction changes.
-- A user may have several historical domains but one primary
-- current journey at a time.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_domain_journeys (
    user_domain_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    domain_id BIGINT NOT NULL,

    development_stage VARCHAR(20) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_domain_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_user_domain_domain
        FOREIGN KEY (domain_id)
        REFERENCES domains (domain_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_development_stage
        CHECK (
            development_stage IN (
                'exploring',
                'aspiring',
                'learning',
                'practicing',
                'professional',
                'expert'
            )
        ),

    CONSTRAINT chk_domain_dates
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);

-- Only one active primary domain journey per user.
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_active_primary_domain
ON user_domain_journeys (user_id)
WHERE is_primary = TRUE
AND ended_at IS NULL;


-- =========================================================
-- 5. JOURNAL PROMPTS
-- Stores reusable guided questions separately from responses.
-- Framework-specific personalization comes later.
-- =========================================================

CREATE TABLE IF NOT EXISTS journal_prompts (
    prompt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    prompt_text TEXT NOT NULL,
    prompt_category VARCHAR(50),
    difficulty_level SMALLINT NOT NULL DEFAULT 1,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_prompt_difficulty
        CHECK (
            difficulty_level BETWEEN 1 AND 10
        )
);


-- =========================================================
-- 6. JOURNAL ENTRIES
-- Private reflection evidence produced by users over time.
-- Public sharing requires deliberate user approval.
-- =========================================================

CREATE TABLE IF NOT EXISTS journal_entries (
    journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    prompt_id BIGINT,

    entry_text TEXT NOT NULL,

    visibility VARCHAR(20) NOT NULL DEFAULT 'private',
    shared_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_journal_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_journal_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES journal_prompts (prompt_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_journal_visibility
        CHECK (
            visibility IN (
                'private',
                'connections',
                'public'
            )
        ),

    CONSTRAINT chk_journal_shared_state
        CHECK (
            visibility = 'private'
            OR shared_at IS NOT NULL
        )
);


-- =========================================================
-- 7. FOCUS SESSIONS
-- Operational flow recording each attempt to focus.
-- =========================================================

CREATE TABLE IF NOT EXISTS focus_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    task_name VARCHAR(200),
    planned_duration_min INTEGER NOT NULL,
    actual_duration_min INTEGER,

    completed BOOLEAN NOT NULL DEFAULT FALSE,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_focus_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_planned_duration_positive
        CHECK (planned_duration_min > 0),

    CONSTRAINT chk_actual_duration_nonnegative
        CHECK (
            actual_duration_min IS NULL
            OR actual_duration_min >= 0
        ),

    CONSTRAINT chk_focus_times
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);


-- =========================================================
-- 8. BUDDY SETTINGS
-- One active Buddy configuration per user.
-- =========================================================

CREATE TABLE IF NOT EXISTS buddy_settings (
    buddy_settings_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    buddy_name VARCHAR(50) NOT NULL,
    buddy_theme VARCHAR(50) NOT NULL,
    sound_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_buddy_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- =========================================================
-- 9. USER ORBIT HISTORY
-- Preserves Orbit progression without exposing private evidence.
-- Recommendation and review logic will be added later.
-- =========================================================

CREATE TABLE IF NOT EXISTS user_orbit_history (
    user_orbit_history_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    orbit_id SMALLINT NOT NULL,

    progression_source VARCHAR(30) NOT NULL DEFAULT 'initial',
    public_summary TEXT,

    awarded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_orbit_history_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_orbit_history_orbit
        FOREIGN KEY (orbit_id)
        REFERENCES orbits (orbit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_progression_source
        CHECK (
            progression_source IN (
                'initial',
                'system_recommendation',
                'human_review',
                'invitation',
                'administrative'
            )
        ),

    CONSTRAINT chk_orbit_history_dates
        CHECK (
            ended_at IS NULL
            OR ended_at >= awarded_at
        )
);


-- =========================================================
-- 10. INDEXES
-- Improve common lookups as the data stocks accumulate.
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_users_current_orbit
ON users (current_orbit_id);

CREATE INDEX IF NOT EXISTS idx_user_domains_user
ON user_domain_journeys (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_journal_entries_user_created
ON journal_entries (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_focus_sessions_user_started
ON focus_sessions (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_orbit_history_user_awarded
ON user_orbit_history (user_id, awarded_at DESC);


COMMIT;