-- =========================================================
-- Gravity Daily Buddy (GDB)
-- PostgreSQL Database Blueprint
-- Version: 1.0
-- Purpose: Core MVP data architecture
-- =========================================================

BEGIN;

-- =========================================================
-- 1. ORBITS
-- Stable reference data defining GDB's six orbit levels.
-- =========================================================

CREATE TABLE IF NOT EXISTS orbits (
    orbit_id SMALLINT PRIMARY KEY,
    orbit_name VARCHAR(100) NOT NULL UNIQUE,
    access_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_orbit_access_type
        CHECK (
            access_type IN (
                'open',
                'paid_test',
                'invitation_only'
            )
        )
);

INSERT INTO orbits (orbit_id, orbit_name, access_type)
VALUES
    (1, 'Parallax Orbit', 'open'),
    (2, 'Standard Candle Orbit', 'open'),
    (3, 'Spectroscopy Orbit', 'paid_test'),
    (4, 'Event Horizon Orbit', 'paid_test'),
    (5, 'Relativity Orbit', 'paid_test'),
    (6, 'Singularity Orbit', 'invitation_only')
ON CONFLICT (orbit_id) DO UPDATE
SET
    orbit_name = EXCLUDED.orbit_name,
    access_type = EXCLUDED.access_type;


-- =========================================================
-- 2. USERS
-- Stores the base account and evolving profile identity.
-- Authentication credentials will be handled separately.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,

    domain_name VARCHAR(100),
    domain_stage VARCHAR(20),

    current_orbit_id SMALLINT NOT NULL DEFAULT 1,
    streak_count INTEGER NOT NULL DEFAULT 0,

    profile_image_url TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_users_orbit
        FOREIGN KEY (current_orbit_id)
        REFERENCES orbits (orbit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_users_streak_nonnegative
        CHECK (streak_count >= 0),

    CONSTRAINT chk_domain_stage
        CHECK (
            domain_stage IS NULL
            OR domain_stage IN (
                'exploring',
                'learning',
                'practicing',
                'established'
            )
        )
);


-- =========================================================
-- 3. JOURNAL ENTRIES
-- Stores reflection evidence over time.
-- Prompted systems questions can be added here immediately.
-- =========================================================

CREATE TABLE IF NOT EXISTS journal_entries (
    journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    prompt_text TEXT,
    entry_text TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_journal_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- =========================================================
-- 4. FOCUS SESSIONS
-- Stores each attempt to focus as a separate event.
-- =========================================================

CREATE TABLE IF NOT EXISTS focus_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,

    duration_min INTEGER NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,

    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ,

    CONSTRAINT fk_focus_session_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_focus_duration_positive
        CHECK (duration_min > 0),

    CONSTRAINT chk_focus_end_after_start
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);


-- =========================================================
-- 5. BUDDY SETTINGS
-- Stores one current Buddy configuration per user.
-- =========================================================

CREATE TABLE IF NOT EXISTS buddy_settings (
    buddy_settings_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL UNIQUE,

    buddy_name VARCHAR(50) NOT NULL,
    buddy_theme VARCHAR(50) NOT NULL,
    sound_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_buddy_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


-- =========================================================
-- 6. INDEXES
-- Improve common searches as the operational stocks grow.
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_users_current_orbit
    ON users (current_orbit_id);

CREATE INDEX IF NOT EXISTS idx_journal_entries_user_created
    ON journal_entries (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_focus_sessions_user_started
    ON focus_sessions (user_id, started_at DESC);


COMMIT;